version: "3.8"
services:
  db: 
    image: dgraph/standalone:latest
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./dgraph-volume
        target: /dgraph
    
        
