# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy_website:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '16.x'
    - name: Install and build
      working-directory: ./website
      run: |
        npm i
        npm run build
        mv build ..
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "build"
        target: "/var/www/stackdb"
        overwrite: true
  populate_db:
    runs-on: ubuntu-latest
    steps:
    - name: Populate the dgraph DB with new yml data
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd stackdb
          docker-compose down
          git pull
          git submodule update --init --recursive
          cd yml_to_graphql
          npm i
          cd ..
          docker-compose -f docker-compose-populate.yml up -d && sleep 15
          ./populate_db.sh
          docker-compose -f docker-compose-populate.yml down
          docker-compose up -d
