# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.4
      with:
        node-version: '16.x'
    - name: Install and build
      working-directory: ./website
      run: |
        npm i
        npm run build
    - name: Copy build files via SSH
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        source: "./website/build"
        target: "/var/www/stackdb"
